# Generated by Django 3.2.5 on 2021-07-30 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimePasscodeSMS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('mobile_number', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=2)),
                ('skip_verification', models.BooleanField(default=False)),
                ('skip_reason', models.TextField(blank=True, null=True)),
                ('otp_dispatched_val', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_confirmed_val', models.CharField(blank=True, max_length=6, null=True)),
                ('attempts_remaining', models.IntegerField(blank=True, default=3, null=True)),
                ('expire_time', models.DateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(blank=True, default=False, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
