# Generated by Django 3.2.5 on 2021-07-31 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_dispatcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onetimepasscodesms',
            old_name='region',
            new_name='country',
        ),
    ]
