# Generated by Django 3.2.5 on 2021-08-01 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_dispatcher', '0004_alter_onetimepasscodesms_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onetimepasscodesms',
            old_name='verfied_datetime',
            new_name='verified_datetime',
        ),
    ]
