# Generated by Django 4.1.1 on 2022-09-27 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_authorisedrepresentative_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('otp_dispatcher', '0007_alter_onetimepasscodesms_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimePasscode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('destination', models.CharField(choices=[('SMS', 'Mobile SMS'), ('EML', 'Email')], max_length=3)),
                ('reason', models.IntegerField(choices=[('1', 'Cancellation of service/account.'), ('2', 'Service block/suspension request.'), ('3', "Adding/Removing a person as a customer's authorised representative."), ('4', 'Disclosure of personal information, business information or account security information relating to the account.'), ('5', 'Additional ongoing or a large one-off charge applied to customers account.'), ('6', 'SIM Swap Request.'), ('7', 'Transfer service from post-paid to prepaid.'), ('8', 'Activation of service request.'), ('9', 'Change of ownership of account.'), ('10', 'Change customer specific detail - DOB, email, contact details, etc.'), ('11', 'Request to block IMEI.'), ('12', 'Request to purchase additional mobile device.'), ('13', 'Request to add additional service to an account.')])),
                ('otp_val', models.CharField(blank=True, max_length=6, null=True)),
                ('attempts_remaining', models.IntegerField(blank=True, default=3, null=True)),
                ('expire_time', models.DateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('verified_datetime', models.DateTimeField(blank=True, null=True)),
                ('auth_rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.authorisedrepresentative')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
