# Generated by Django 4.1.1 on 2022-09-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_dispatcher', '0008_onetimepasscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepasscode',
            name='reason',
            field=models.IntegerField(choices=[(1, 'Cancellation of service/account.'), (2, 'Service block/suspension request.'), (3, "Adding/Removing a person as a customer's authorised representative."), (4, 'Disclosure of personal information, business information or account security information relating to the account.'), (5, 'Additional ongoing or a large one-off charge applied to customers account.'), (6, 'SIM Swap Request.'), (7, 'Transfer service from post-paid to prepaid.'), (8, 'Activation of service request.'), (9, 'Change of ownership of account.'), (10, 'Change customer specific detail - DOB, email, contact details, etc.'), (11, 'Request to block IMEI.'), (12, 'Request to purchase additional mobile device.'), (13, 'Request to add additional service to an account.')]),
        ),
    ]
