# Generated by Django 4.1.1 on 2022-09-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_dispatcher', '0009_alter_onetimepasscode_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepasscode',
            name='dest_value',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
