# Generated by Django 4.1.1 on 2022-09-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_dispatcher', '0010_onetimepasscode_dest_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepasscode',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
