# Generated by Django 4.1.1 on 2022-09-21 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_auth1_country_client_auth2_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='aut1_mobile',
            new_name='auth1_mobile',
        ),
    ]
