# Generated by Django 4.1.1 on 2022-09-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_rename_aut1_mobile_client_auth1_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='auth1_country',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='client',
            name='auth2_country',
            field=models.CharField(blank=True, default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='client',
            name='auth2_email',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='auth2_firstname',
            field=models.CharField(blank=True, default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='auth2_mobile',
            field=models.CharField(blank=True, default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='client',
            name='auth2_surname',
            field=models.CharField(blank=True, default=None, max_length=254),
        ),
    ]
