# Generated by Django 4.1.1 on 2022-09-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_authorisedrepresentative_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorisedrepresentative',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
